### ISSUE TITLE
Localization : Support world-wide title, original title and localized title

### ISSUE THREAD

**Issue by nliautaud** [nliautaud/trakttvstats#14]
The movie page title could show up to three different titles : the world-wide title as indicated by Trakt, the original title and a localized title. The movies thumbs would show up to two of them.

**Display :** The alternate titles are shown one below the other, according to the options.
- In a movie page one title would be shown as the header, along with the date and other infos, and the other titles would be shown below as sub-headings, pointing out their origin (see [imdb](http://www.imdb.com/title/tt0260991/)).
- The movies thumbs would show a main one, and another below.

**Options :** The options allow to choose which title to show and in what order.
- Original title (select) : Don't show (default) / Display below / Display first
- *The localization language enable the following options :*
- Show the localized title first (checkbox)

Localization options/Original title | Don't show | Display below | Display first
---|---|---|---
Localization disabled | **The Movie _2000_** | **The Movie _2000_**<br>영화 _(original title)_ | **영화 _2000_**<br>The Movie _(world-wide title)_
Localization enabled | **The Movie _2000_**<br>Le Film _(FR)_ | **The Movie _2000_**<br>영화 _(original title)_<br>Le Film _(FR)_ | **영화 _2000_**<br>The Movie _(world-wide title)_<br>Le Film _(FR)_
Localized title first | **Le Film _2000 (FR)_**<br>The Movie _(world-wide title)_ | **Le Film _2000 (FR)_**<br>The Movie _(world-wide title)_<br>영화 _(original title)_ | **Le Film _2000 (FR)_**<br>영화 _(original title)_<br>The Movie _(world-wide title)_

These options give some possibilities without using a more complex input. But a more advanced UX could be a **drag-and-drop list ordering**, with a "disabled-pool" where the different options could be taken from or moved to. This would allow more possibilities, including the use of localized title only, original title only, etc.

**Technical notes**

When the original title is required, TMDb would be called even without a language code given.  And the "on page load" / "on hover" setting should be accessible in such case.

- World-wide title : Trakt title
- Original title : TMDb API ``original_title``
- Localized title : TMDb API ``title`` (exists if ``i18nLang`` is set) or ``alternatives_titles.title`` (appended trough ``append_to_response``)

The corresponding ``alternatives_titles`` seems to be more correct than the localized ``title``. The second could be used as a fallback for the first if necessary. Ex: *Joint Security Area* gives *JSA (Joint Security Area)* as french title and *JSA, Joint Security Area* as french alternative_title.

**Issue/remarks**

- The original title return the non-westernized title (ex. *공동경비구역 JSA*). The westernized original title may be present in alternate_titles (ex. *Gongdong gyeongbi guyeok JSA*), but is not marked as "original" so cannot be retrieved reliably.

*Original suggestion by @chatterer on August 29, 2017 on [chrome webstore](https://chrome.google.com/webstore/detail/trakt-improver-dev/ppeoegnflhlfjkclghpfkgpgpbodlaaa/support?utm_source=chrome-app-launcher-info-dialog)*

**Comment by nliautaud** [comment]
Implemented custom ordering and selection UX and logic in 0.5 branch.

![2017-09-25 19_48_05-](https://user-images.githubusercontent.com/761761/30822871-93874e36-a22a-11e7-9e1b-66f3a3189f0f.png)

The first one checkbox could be hidden, as the main title line is always shown.

**Comment by chatterer** [comment]
wow, this is great

![1](https://user-images.githubusercontent.com/3000715/30824104-bbaca07e-a22e-11e7-81a0-3d9f37dcdef0.png)

could you please update the chrome-dev-channel with v0.5? much better for updates.

**Comment by chatterer** [comment]
tested with some other movies and it looks fine

**Comment by nliautaud** [comment]
Great, thanks for your support !
I'll update the dev channel after releasing the current dev into the main channel, which should be in the following days if no major bug is found.
Didn't planned that you would test the dev branch directly :)
