### ISSUE TITLE
breaks progress bar on dashboard

### ISSUE THREAD

**Issue by chatterer** [nliautaud/trakttvstats#17]
under "up next to watch"
![img](http://cdn-images-1.medium.com/max/1000/1*DhXIxQotk4ROlBiGpMoKyA.png)

**Comment by nliautaud** [comment]
Hi, thanks for your reports !

- Could you tell me which channel of the plugin do you use (official or dev) and which version, in `chrome://extensions` ?
- Could you provide an url where I may see the issue, or explain what the issue is/shouldn't do ? Note that I don't have trakt VIP.

**Comment by chatterer** [comment]
Trakt improver DEV 0.4 alpha (0.4.0.21)

![tg9ah2hqua_l](https://user-images.githubusercontent.com/761761/30753909-0ffdb2fa-9fc1-11e7-8c39-c719720fa3b0.png)

**Comment by nliautaud** [comment]
Thanks, confirmed as a bug raised by *Multiline title* option.

*PS: I edited your comments to display the images. Note that you can attach files directly on github*

**Comment by chatterer** [comment]
I have to thank

**Comment by nliautaud** [comment]
Fix will be live soon on DEV (0.4.0.21).
