### ISSUE TITLE
Add Collected and listed support in the charts

### ISSUE THREAD

**Issue by JasonGantner** [nliautaud/trakttvstats#6]
Your add-on is great and I think adding (in a different color or in an inner/outer circle) the amount of listed and collected movies to the chart would be awesome (if possible) :smiley:

**Comment by nliautaud** [comment]
To celebrate the first anniversary of this issue the v0.4 is in its way to include statistics and filters supports for ratings, collections and lists :)

![2017-08-23 18_58_50-ben stiller - trakt tv](https://user-images.githubusercontent.com/761761/29628337-70853254-8835-11e7-8b81-820442bbd5c1.png)
![2017-08-23 18_59_06-ben stiller - trakt tv](https://user-images.githubusercontent.com/761761/29628341-71d0e54a-8835-11e7-9dc1-c99debac1766.png)

**Comment by JasonGantner** [comment]
Wow that looks awesome!

**Comment by nliautaud** [comment]
I'll wait for a few time before releasing it, as I'm the only tester, but feel free to get the latest if you want to give a try ! https://github.com/nliautaud/trakttvstats/archive/0.4.zip

**Comment by nliautaud** [comment]
Feature available in the v0.4 alpha, released for testing in dev extension :   
https://chrome.google.com/webstore/detail/trakt-improver-dev/ppeoegnflhlfjkclghpfkgpgpbodlaaa
